# Travis continuous integration configuration file
language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install python-coveralls
script:
  - pytest --cov=mitxgraders --cov-report=term-missing
after_success:
  - coveralls
