site_name: MITxGraders
repo_url: 'https://github.com/mitodl/mitx-grading-library'
edit_uri: ''
pages:
  - Home: 'index.md'
  - Getting Started:
    - Getting Started: 'getting_started.md'
    - ItemGrader: 'item_grader.md'
    - StringGrader: 'string_grader.md'
  - Grading Math:
    - FormulaGrader: 'grading_math/formula_grader.md'
    - NumericalGrader: 'grading_math/numerical_grader.md'
    - MatrixGrader: 'grading_math/matrix_grader/matrix_grader.md'
    - Sampling Sets: 'grading_math/sampling.md'
    - Function List: 'grading_math/function_list.md'
    - AsciiMath Renderer Definitions: 'grading_math/renderer.md'
  - Grading Lists:
    - ListGrader: 'grading_lists/list_grader.md'
    - SingleListGrader: 'grading_lists/single_list_grader.md'
  - Changelog: 'changelog.md'
markdown_extensions:
    - toc:
        permalink: "\uF0C1"
    - admonition
extra_css:
  - css/extra.css
